### ISSUE TITLE
Do we still need vagrant-atomic plugin

### ISSUE THREAD

**Issue by langdon** [projectatomic/adb-atomic-developer-bundle#114]
I believe that we do not need the [vagrant-atomic pluigin](https://github.com/projectatomic/vagrant-atomic) anymore. However, we need some confirmation and testing to be sure.

**Comment by strzibny** [comment]
`vagrant-atomic` deals with Atomic guests and the support is merged in Vagrant 1.7.3 which means that on Fedora 22 we still need the plugin to be installed in order to recognize Atomic.

On the other hand, ADB itself uses regular CentOS 7.1 as a guest right? If ADB does not build on top of Atomic, then the plugin is not needed for the setup...

**Comment by langdon** [comment]
@strzibny could you look in to updating the [readme](https://github.com/projectatomic/vagrant-atomic/blob/master/README.md) to reflect this information? @bexelbie or @LalatenduMohanty do you want to update the [adb- readme](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/README.rst) to reflect the above?

**Comment by strzibny** [comment]
@whitel I will do. Edit: Done.
