### ISSUE TITLE
vagrant adbinfo does not always contain host name

### ISSUE THREAD

**Issue by maxandersen** [projectatomic/adb-atomic-developer-bundle#136]
not sure when it fails, but earlier today `vagrant adbinfo` worked fine, but now I get this:

```
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:

export DOCKER_HOST=tcp://:2376
export DOCKER_CERT_PATH=/Users/max/code/cdk/.vagrant/machines/default/virtualbox/.docker
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=a58fb70

# run following command to configure your shell:
# eval "$(vagrant adbinfo)"
```

notice that host is blank/not-specified.

**Comment by maxandersen** [comment]
running with debug I see it outputs this error:

```
DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: Execute: ip addr show eth1 | awk 'NR==3 {print $2}' | cut -f1 -d/ (sudo=false)
DEBUG ssh: stderr: Device "eth1" does not exist.
```

any idea why it uses eth1 and not eth0 ?

**Comment by maxandersen** [comment]
i.e. `ip addr show eth0 |  awk 'NR==3 {print $2}' | cut -f1 -d/` works.

**Comment by hferentschik** [comment]
> any idea why it uses eth1 and not eth0 ? 

Because _eth1_ is usually the interface used for the host only private network. _eth0_ is used for the default net access. If you used our OpenShift Vagrant setup with private networking, it should have worked. Not sure why the interface was not created.

So even though I am not sure what was going on in your case,  I would agree that there is an issue here.
Looking at the [code](https://github.com/projectatomic/vagrant-adbinfo/blob/master/lib/command.rb#L45):

```
command = "ip addr show eth1 | awk 'NR==3 {print $2}' | cut -f1 -d\/"
```

it just assumes 'eth1' per default. This means the NAT only approach is not going to work. Fair enough for me. since I think the private network approach is the better one. The question is what  ADB wants to support out of the box. Here adbinfo makes assumptions about how Vagrant is configured and created a dependency between the Vagrant configuration and adbinfo. 

If ADB considers both cases (NAT only or NAT + private network) valid, then the script needs to be a bit smarter here and check the configuration and network interfaces. 

If the intention is to enforce private networking (not allowing NAT only), then there should be some error checking here. If no private network is configured or _eth1_ is for some reason not created _adbinfo_ should report an error. This would be also generally helpful for ADB users, since it would help tracking down issues. _adbinfo_ becomes to a part also a sanity check of the running VM.

**Comment by hferentschik** [comment]
This issue should be moved to here - https://github.com/projectatomic/vagrant-adbinfo/issues

**Comment by maxandersen** [comment]
recreating the box to verify/confirm. might have used this on something that was not the latest cdk.

**Comment by navidshaikh** [comment]
Kindly submit any subsequent issue(s) for vagrant-adbinfo plugin at https://github.com/projectatomic/vagrant-adbinfo/issues
