### ISSUE TITLE
ADB should include atomicapp

### ISSUE THREAD

**Issue by jberkus** [projectatomic/adb-atomic-developer-bundle#307]
Recently one of our extented team submitted a blog post for using Mesos with the ADB.  In the post, he recommends compiling atomicapp from source, because apparently there's no other way to use it in the ADB:  https://github.com/projectatomic/atomic-site/pull/279

... and he's rigtht.  This is bad; our tools should work together.  Developers should be able to create atomic apps using the ADB.

So, given that atomicapp is still in heavy development, what's the best way to include it in the ADB so that it can be used there?

**Comment by dustymabe** [comment]
We had this conversation in IRC but I just want to add this here so this can be part of the discussion that we have here. There are three ways to run an atomicapp described by the files in your local directory:
- native atomic app installation
  - atomicapp run .
- running via atomic cli
  - atomic run projectatomic/atomicapp .
- running via a container with (an alias is used to help)
  - alias aa='docker run -it --rm  --privileged -v $(pwd):/atomicapp -v /run:/run -v /:/host --net=host --name atomicapp projectatomic/atomicapp:latest'
  - aa run .

That being said, should we have atomicapp software installed in the ADB/CDK? Probably.

**Comment by bexelbie** [comment]
It appears @LalatenduMohanty is the maintainer in Fedora.  Is there an RPM in CentOS for this yet?  We would need it there it seems and ideally part of an RCM process somewhere.

**Comment by jberkus** [comment]
BTW, I'll note that the ADB documentation _says_ that it includes Atomic App.

**Comment by praveenkumar** [comment]
>  Is there an RPM in CentOS for this yet? 

https://cbs.centos.org/koji/packageinfo?packageID=1830 it is there but need update. I was able to do a scratch build for 0.4.5 version https://cbs.centos.org/koji/taskinfo?taskID=84633 but don't have permission for tag build https://cbs.centos.org/koji/taskinfo?taskID=84635 ( @navidshaikh or @LalatenduMohanty  might able to do it)

**Comment by LalatenduMohanty** [comment]
Sorry for the late reply. I am not sure whether AtomicApp should be part of ADB or not as this not a use case all users of ADB would need. Because we have AtomicApp container to cover most of the use cases. However I can understand @jberkus 's concern about the Mesos use case and I agree that we need to improve the user experience there.  So here is my suggestion
- Build AtomicApp in CentOS for ADB and make them available in http://mirror.centos.org/centos-7/7/atomic/x86_64/adb/
- ADB by-default has  yum repository configured for http://mirror.centos.org/centos-7/7/atomic/x86_64/adb/ . so a simple `yum install atomicapp`  would install it. 
- We can add the `yum install atomicapp -y` to https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos/centos-mesos-marathon-singlenode-setup 

Let me know what you think? \CC @dharmit

**Comment by LalatenduMohanty** [comment]
Also if we have documented that ADB contains AtomicApp we should remove/fix it.

**Comment by dharmit** [comment]
Installing `atomicapp` at the time of provisioning seems appropriate to me. I can add `atomicapp` to the [ansible playbook](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-mesos-marathon-singlenode-setup/provisioning/playbook.yml) being used to provision mesos marathon on ADB.

**Comment by bexelbie** [comment]
+1 for install at provisioning by @dharmit

**Comment by bexelbie** [comment]
What is our default way of running Atomic App with ADB?

Why does only Mesos require an install and everything else can do something else?

**Comment by dharmit** [comment]
> Why does only Mesos require an install and everything else can do something else?

I'm not sure if only Mesos requires it. But Mesos requires it because the `atomic` cli doesn't support Mesos-Marathon provider. `atomicapp` does.

**Comment by bexelbie** [comment]
> I'm not sure if only Mesos requires it. But Mesos requires it because the atomic cli doesn't support Mesos-Marathon provider. atomicapp does

Do we want to have different ways of handling atomic apps for different providers?  Could Mesos-Marathon use the atomicapp container?

**Comment by jberkus** [comment]
This has nothing to do with Mesos.  AtomicApp is one of our container developer tools.  It should be in the ADB, period. As should all of our developer tools.

**Comment by LalatenduMohanty** [comment]
@jberkus Yes to developer tools in ADB. But I am not sure if AtomicApp is a developer or an ISV tool. Also we are struggling with higher size of the Vagrantbox. So if we have an alternative as docker images/containers so why not use the docker container unless keeping the tool local to the box has significant advantage in user experience.

**Comment by jberkus** [comment]
Because it's a PITA to execute in a container, and that's not how one would normally use it.  See the discussion above on what the command looks like in vs. outside container.  If you can solve that, then it's no problem to have it in a container.

**Comment by bexelbie** [comment]
This drives back to usage patterns.  Today we have done a ton of work to make the ADB a box that is used via CLI commands, not via `vagrant ssh`.  Today the `atomic` command doesn't work well as a CLI for an external box.  I've done some provisional work on this, but it got dropped in a time crunch.

So, how should a user interact with an atomic application in the ADB?  Should this require `vagrant ssh` or should they be able to launch it like any other container?  This answer guides whether we include atomicapp in the box or not and how we tell people to get it working.

I vote for making atomic work for this use case and not doing anything involving `vagrant ssh`.

**Comment by LalatenduMohanty** [comment]
> Do we want to have different ways of handling atomic apps for different providers?

Nope. But do we have a choice right now?

> Could Mesos-Marathon use the atomicapp container?

Nope.  Because atomicapp container is strongly tied with atomic CLI. So as @dharmit said, mesos directly uses atomicapp CLI instead of atomic.

**Comment by LalatenduMohanty** [comment]
> So, how should a user interact with an atomic application in the ADB? Should this require vagrant ssh or should they be able to launch it like any other container? This answer guides whether we include atomicapp in the box or not and how we tell people to get it working.
> 
> I vote for making atomic work for this use case and not doing anything involving vagrant ssh.

+1 for making atomic work for this use case. But question is who will do the work? Should ADB project invest in this?  not sure. But is it a priority for ADB? IMO no.

**Comment by LalatenduMohanty** [comment]
Atomicapp has been added to ADB  YUM repo [1]. It should be soon available in mirror.c.o [2] after it is signed and pushed by CentOS project. Now `yum install atomicapp` can install atomicapp to ADB.

[1] http://cbs.centos.org/repos/atomic7-adb-common-release/x86_64/os/Packages/
[2] http://mirror.centos.org/centos-7/7/atomic/x86_64/adb/

This partially solves the issue for which this was raised. I am against making atomicapp as part of default set of packages because :
- Only Mesos needs it, but k8s and OpenShift does not need it.
- We are struggling to keep the size of Vagrantbox low.
- With recent discussions, there is some change in Atomicapp's direction. So until we are not sure how the new direction is related to ADB we should not make  it part of default set of packages. 

Should I close the issue now?

**Comment by jberkus** [comment]
Sure, seems solved.
