### ISSUE TITLE
Update 'README_CDK_ZIP.adoc' content to reflect all docs in .adoc formats

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-atomic-developer-bundle#561]
Hi,

[README_CDK_ZIP.adoc](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/README_CDK_ZIP.adoc) content contains repo docs main in `.md` format. 
Update it to reflect the changes of `.adoc` format.

**Comment by bexelbie** [comment]
I believe this readme is delivered as plain unrendered text to users. Should this be converted?

**Comment by brgnepal** [comment]
@thatdocslady What's your thought mikey?

**Comment by thatdocslady** [comment]
@budhrg @bexelbie this file was already converted, and regardless the links should point to the correct files, especially since they're all readmes and will be accessed via GitHub. I'll add the link fixes to the existing issue for post-conversion fixes #560, I don't think we need a separate issue for this.

**Comment by brgnepal** [comment]
@thatdocslady Cool then we can do that as part of cleanup part. Closing it now.
