### ISSUE TITLE
Repo required for python-sqlalchemy is missing in vagrant image build command

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#71]
While building vagrant box image at koji, `python-sqlalchemy` package is pulled as dependency for the enlisted packages to be installed in the image. 
Repos specified in the koji image build command does not contain `python-sqlalchemy` package, causing the image to fail, unless added a repo having the package in question.

**Comment by LalatenduMohanty** [comment]
@navidshaikh I know about this issue . Check https://bugs.centos.org/view.php?id=9245

The issue is the package did not come from upstream i.e. RHEL initailly.  Then CentOS devs has fixed it. AFAIK you should not see this issue unless the build root has not been rebuilt after python-sqlalchemy  landed up in CentOS repos.

**Comment by LalatenduMohanty** [comment]
@navidshaikh Can you please point me to the failed koji build?

**Comment by navidshaikh** [comment]
@LalatenduMohanty : http://cbs.centos.org/koji/taskinfo?taskID=16953 
The issue is solved from CentOS repo side in between filing this issue and the time I triggered above build. 
Closing this, thanks!

**Comment by LalatenduMohanty** [comment]
cool :)
